### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by Dontorpedo** [antonioribeiro/nova-boolean-datetime-field#1]
Sorry for bothering, how can i use this field?

i like something like: 

if date is in the past, its false, today or in future its true..

**Comment by antonioribeiro** [comment]
Install instructions in readme are not helping? It's all you have to do, pretty much.

**Comment by Dontorpedo** [comment]
i made two entrys for testing..

one in the past

one in the future,

both are true

**Comment by antonioribeiro** [comment]
This component field seves as a boolean for states based on date or datetime, let's say you have a `sent_at` date in your database but you would like to know if the message was sent. 

When the date is null, it was not (red), when the date is filled, it means the message was sent (green).

If you fill both records, both will show it as sent (true - green).

**Comment by Dontorpedo** [comment]
oh ok, thanks
