### ISSUE TITLE
Declaration of BooleanDatetime::nullable

### ISSUE THREAD

**Issue by atmonshi** [antonioribeiro/nova-boolean-datetime-field#2]
hi,
after updating to nova 2.0 , I got this error : 

`Declaration of PragmaRX\BooleanDatetime\BooleanDatetime::nullable() should be compatible with Laravel\Nova\Fields\Field::nullable($nullable = true, $values = NULL)`

my Code is : 

```
use PragmaRX\BooleanDatetime\BooleanDatetime;

BooleanDatetime::make('Is Active?', 'email_verified_at')->nullable()
```
even if I remove the `nullable` .

**Comment by aemaddin** [comment]
same problem again with Laravel 6.2.0 and nova 2.4.0

please remove the nullable method from BooleanDatetime class, when I removed it it's work just fine.

Thanks
