### ISSUE TITLE
How to get working with Nova 2?

### ISSUE THREAD

**Issue by ncatanchin** [antonioribeiro/nova-boolean-datetime-field#4]
Hi, thanks for a nice addon.

I can't see how to get this updated to the latest code that would allow it to be compatible with Nova v2.0?

Have tried:

* `composer update`
* `composer upgrade pragmarx/nova-boolean-datetime-field`
* `composer require pragmarx/nova-boolean-datetime-field@dev-master`

I guess I could target the exact commit reference - is there a more appropriate way to go about it?

Thanks

----

UPDATE: Did some proper looking into it, found this to work:

`composer require pragmarx/nova-boolean-datetime-field:dev-master`

Cheers

**Comment by ziming** [comment]
Wonder what stops it from being tagged as a release though
